Added versioning

diff --git a/.github/workflows/pipe.yml b/.github/workflows/pipe.yml
--- a/.github/workflows/pipe.yml
+++ b/.github/workflows/pipe.yml
@@ -9,23 +9,35 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Login to Docker Hub
+
+      - name: Testing Bash env var
+        run:  | 
+          VERSION=$(cat ./VERSION)
+          if [ -z $VERSION ]; then
+            echo "Version in empty. Aborting."
+            exit 1
+          fi
+          echo $VERSION >> $GITHUB_ENV
+
+      - name: Check variable
+        run:  | 
+          echo $VERSION
+
+      - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Set up Docker Buildx
+
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      -
-        name: Build and push
+
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./Dockerfile
           push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/revapi:testing-ga
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/revapi:$VERSION
